language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build-all-development
  - npm run build-all-production
  - npm run test-ci
before_deploy:
  - openssl aes-256-cbc aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: continuous-deployment
